### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by dvhthomas** [ruby-oauth/oauth2#12]
I'm attempting to write a simple Facebook query app in Sinatra. I've basically started with your example Sinatra code and keep getting the same error: OpenSSL::SSL::SSLError at /auth/facebook/callback. SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. My FB app has the callback URL pointing to http://localhost:4567/auth/facebook/callback and I'm getting a response from FB with the code param: 127.0.0.1 - - [31/Jul/2010 17:58:38] "GET /auth/facebook/callback?code=6a10b78cb4719d350c2d0727-568006959%7CvW32Ylo8_L7X
WXssVIeqvQCOOqQ. HTTP/1.1" 500 114401 0.5220.

I'm brand new to Ruby, Sinatra, and OAuth so if this is a pitiful explanation, my apologies. If this is a bug I'd be interested to hear what might be going wrong. If it's because I just don't know what the heck I'm doing, then feel free to ignore me. Thanks. Oh, running Webrick on Windows, Ruby 1.9.

**Comment by KelseyDH** [comment]
I had to do this to get it working:

```ruby

 @oauth_client = OAuth2::Client.new(@client_id, @client_secret, site: ENV.fetch("TOKEN_SITE_ENDPOINT"), token_url: "path/to/token", ssl: { client_cert: OpenSSL::X509::Certificate.new(ENV["SSL"]), client_key:  OpenSSL::PKey::RSA.new(ENV["KEY"])})
```
