### ISSUE TITLE
getaddrinfo: No such host is known with Rail 4 on Windows 7

### ISSUE THREAD

**Issue by srbhakta** [ruby-oauth/oauth2#187]
While calling get_token for facebook I am getting error
Faraday::ConnectionFailed (getaddrinfo: No such host is known. )

client.auth_code.get_token(
                options[:code],
                :redirect_uri => options[:callback] || @callback,
                :parse => :query
            )

**Comment by xtagon** [comment]
@motobhakta Is this still an ongoing issue? If so, please share steps to reproduce including the options passed to the client instance.
